### ISSUE TITLE
PyUnitWizard/setup.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by alyferryhalo** [uibcdf/PyUnitWizard#45]
According to [this instruction](https://www.uibcdf.org/PyUnitWizard/contents/about/installation.html#developing-version-from-the-source-code), there is a way to install PyUnitWizard like this:

```
git clone https://github.com/uibcdf/PyUnitWizard.git
cd PyUnitWizard
python setup.py develop
```

But actually there is no `setup.py` file in repo. How to fix it?

**Comment by dprada** [comment]
Hi Alisa (@alyferryhalo): 
You are right. It is something we have to fix as soon as possible. The use of a `setup.py` is going to be deprecated soon (it may be already).

The instructions to work with the dev version are:

```
git clone https://github.com/uibcdf/PyUnitWizard.git
cd PyUnitWizard
pip install --editable .
```

With the option "editable" you can play with the code.

If you want a "stable" version -and you are working with conda environments-:

```
conda install -c uibcdf pyunitwizard
```

Let us know if you have any other problems.

**Comment by dprada** [comment]
This issue was replied and there were no further comments.
Let's close it.
Thanks for your feedback!
